### ISSUE TITLE
[BUG] - vSTARS to CRC coord without decimal throws issue

### ISSUE THREAD

**Issue by KSanders7070** [Nikolai558/FE-BUDDY#101]
![image](https://user-images.githubusercontent.com/63331106/204402292-14bf0aa9-ee63-4e59-8250-09cb91cb60cd.png)

**Comment by KSanders7070** [comment]
Correction:
xsi:type="Label" is throwing an error. Solution: Skip anything that isn't xsi:type="Line"

**Comment by Nikolai558** [comment]
fixed in 2.3.4
