### ISSUE TITLE
[TODO] - Rewrite Instructions to install section

### ISSUE THREAD

**Issue by KSanders7070** [Nikolai558/FE-BUDDY#107]
Users of FE-Buddy version 2.0 or greater, should launch the program and allow it to auto-update.
If this is a fresh/new install, please Download and run the FE-BUDDYSetup.exe and follow the prompts to install.

```
Hyperlink "FE-BUDDYSetup.exe" with the following hyperlink:
https://github.com/Nikolai558/FE-BUDDY/releases/latest/download/FE-BUDDYSetup.exe
```

**Comment by Nikolai558** [comment]
completed
