### ISSUE TITLE
[FEAT REQ.] - AWY GEOMaps Style to SOLID

### ISSUE THREAD

**Issue by KSanders7070** [Nikolai558/FE-BUDDY#108]
Requesting the AWY_HI_GEOMAP.xml and AWY_LO_GEOMAP.xml line defaults for "Style" to be:
`Style="Solid"`

**Comment by Nikolai558** [comment]
Completed, will be in next release.

**Comment by Nikolai558** [comment]
https://github.com/Nikolai558/FE-BUDDY/releases/tag/2.3.7
