### ISSUE TITLE
[BUG] - Info buttons linked to "Releases" branch

### ISSUE THREAD

**Issue by KSanders7070** [Nikolai558/FE-BUDDY#112]
When I edit the Roadmap and Credits data, I edit it in the Development branch but the buttons in the program take you to the Releases branch. I think it would be better if they were linked to the Dev branch.

**Comment by Nikolai558** [comment]
Completed, will be in next release.

**Comment by Nikolai558** [comment]
https://github.com/Nikolai558/FE-BUDDY/releases/tag/2.3.7
