### ISSUE TITLE
[FEAT REQ.] - vERAM GeoMapObjects combined to Filter Index

### ISSUE THREAD

**Issue by KSanders7070** [Nikolai558/FE-BUDDY#113]
Provide the user with an option to combine all GeoMapObjects that display per Filter Index into a single GeoJSON.

It will not be as simple as just combining ALL data that is assigned to a specific filter to a GeoJSON, as many GeoMapObjects are assigned different values such as xsi:type, brightness control groups, size, underline, x/y offsets, etc... that the user will want to have more control over with the vNAS admin site. Therefore, we will need to group all GeoMapObjects that share identical Filter Indexes AND other attributes into a single GeoJSON.

This will allow the user to manage the data more easily when renaming the files to more a local naming syntax and more assurance of accuracy when uploading to vNAS.

Also note that many facilities will assign a geomapobject to multiple Filter Indexes. This will lead to duplicate data but that is acceptable.

**Comment by KSanders7070** [comment]
The attached zip file includes an example directly & file handling example with a explanative readme file.
[GeoJSON per Index Project.zip](https://github.com/Nikolai558/FE-BUDDY/files/10332640/GeoJSON.per.Index.Project.zip)

**Comment by Nikolai558** [comment]
Completed in Version 2.4.0
