### ISSUE TITLE
[BUG] - Index out of bounds on Get Airac Data

### ISSUE THREAD

**Issue by wiggleforlife** [Nikolai558/FE-BUDDY#125]
**Describe the bug**
Index out of bounds immediately after running.

**To Reproduce**
1. Run Get AIRAC Data with 2213/2301 and Convert East Coordinates

**Expected behavior**
Program gets AIRAC data as usual

**Screenshots**
![image](https://user-images.githubusercontent.com/46230102/213335320-4e492c5e-fc0d-429d-9298-bf85e63aa28b.png)
![image](https://user-images.githubusercontent.com/46230102/213335364-0385cb35-2882-4855-95f5-d4716b11ff98.png)
[FE-BUDDY_LOG.txt](https://github.com/Nikolai558/FE-BUDDY/files/10452663/FE-BUDDY_LOG.txt)

**Comment by Nikolai558** [comment]
Thank you for this bug report! 

It is a valid bug that was introduced in this [commit](https://github.com/Nikolai558/FE-BUDDY/commit/f433f236e4e3d329d9a8ae3e18853929154cf35e)

I did not fully make the changes necessary to have the AIRAC dates and cycles displayed. Hopefully with the refactor I am planning soon these kind of mistakes won't happen again. I am working on a hot fix for this now.

**Comment by Nikolai558** [comment]
This has been fixed and will be in the next release. Thanks.
