### ISSUE TITLE
[BUG] - Not All Lines are drawn

### ISSUE THREAD

**Issue by Nikolai558** [Nikolai558/FE-BUDDY#127]
**Describe the bug**
When using the vERAM to geojson conversion option with the output by filter and properties, not all lines were being drawn.
see screenshots below.

**Screenshots**

Wrong: 
![image](https://user-images.githubusercontent.com/38259407/213624176-72fdd9aa-bbe8-47bb-a320-1d37cdbbb417.png)

Should be:
![image](https://user-images.githubusercontent.com/38259407/213624209-fb7b7bfc-51f2-4b0c-bd0c-8c85ebc38517.png)

**Comment by KSanders7070** [comment]
Could this be because the missing lines have overriding attributes for those segments in the .xml and therefore are putting them into another file?

**Comment by Nikolai558** [comment]
No it was something in the code with 2.4.1.

This has been fixed in v2.4.2
