### ISSUE TITLE
[BUG] - sct2-geojson out of array

### ISSUE THREAD

**Issue by nshuster312** [Nikolai558/FE-BUDDY#140]
![BUG REPORT](https://user-images.githubusercontent.com/126917718/222831017-69d43620-2cf5-4501-aec6-3847a4fcd7aa.jpg)

[huf101sgp.sct2.txt](https://github.com/Nikolai558/FE-BUDDY/files/10886177/huf101sgp.sct2.txt)

gethub will not allow me to upload sct file so I renamed it to txt file

**Comment by KSanders7070** [comment]
Further investigation narrowed the issue down to the ZID "INFO" section data. FEB doesn't like it for some reason. If you replace it with the ZLC data, it works just fine.

**Comment by KSanders7070** [comment]
![image](https://user-images.githubusercontent.com/63331106/222834783-ca035941-79f8-42cf-b6d9-d9c9f918c993.png)
They are missing the "Scaling factor" which should be optional but I would also wonder why FEB even cares what is in the INFO section, as there is no obvious use for this data in my opinion.

**Comment by Nikolai558** [comment]
This has been fixed in version v2.6.2
