### ISSUE TITLE
[BUG] - is?Defaults only transfers 1 of the defaults in a geomap object

### ISSUE THREAD

**Issue by KSanders7070** [Nikolai558/FE-BUDDY#156]
This one takes the second set of defaults and makes a Is?Defaults feature at the beginning of the file but skips the first set of defaults:
![image](https://github.com/Nikolai558/FE-BUDDY/assets/63331106/c335b21f-1b13-4937-88fe-6678ffa970f4)

This one makes a Is?Defaults at the beginning of the file but then makes a Is?Defaults for the second set of defaults and puts it in each of the features to follow:
![image](https://github.com/Nikolai558/FE-BUDDY/assets/63331106/1e400a0e-101b-4e8e-b279-6f43585ec306)

**Comment by KSanders7070** [comment]
Every time the XSI type is a LINE, FEB makes two isLineDefaults features. One at the beginning, and another after the first actual feature:
![image](https://github.com/Nikolai558/FE-BUDDY/assets/63331106/24a3880e-2a2e-462a-aceb-e5e9d7adb12b)

**Comment by KSanders7070** [comment]
3nm RINGS
 -Exports a normal line only file except the LINE issue where there are two different is?Defaults features.

TERRAIN ALERT VOLUME TAV
 -Exports the text data normally because it has isTextDefaults at the beginning but lacks a isLineDefaults at the begining resulting in CRC not displaying the lines.

WX STATIONS
 -Exports a normal text only file and nothing is wrong.

ZLC WX STATIONS
 -Exports a file that has the isTextDefaults at the beginning only once however then inserts isSymbolDefaults into EACH of the symbol features.
[Output Geojsons.zip](https://github.com/Nikolai558/FE-BUDDY/files/12570945/Output.Geojsons.zip)

**Comment by KSanders7070** [comment]
> 

[ZLC GeoMaps.xml.txt](https://github.com/Nikolai558/FE-BUDDY/files/12570963/ZLC.GeoMaps.xml.txt)
This is a test file that contains only the aforementioned geomap objects for easier testing. Rename the file to remove the .txt.

**Comment by Nikolai558** [comment]
fixed v.2.6.7
