### ISSUE TITLE
[BUG] - AIRAC Cycle Showing Twice

### ISSUE THREAD

**Issue by KSanders7070** [Nikolai558/FE-BUDDY#161]
![image](https://github.com/Nikolai558/FE-BUDDY/assets/63331106/09902b3e-cecd-4c01-9e52-2a8466914132)

After selecting the radio button for what SHOULD be the next cycle, I find that it does actually grab the old/current cycle data:
![image](https://github.com/Nikolai558/FE-BUDDY/assets/63331106/b36c4b29-c55d-472e-a0d2-ced3e456d238)

I thought it might be a problem with my list of cycles and dates but nope...
![image](https://github.com/Nikolai558/FE-BUDDY/assets/63331106/75371e73-bd95-43fc-9b77-bcb724ed525f)

The downloaded HTML file looks right, too...
![image](https://github.com/Nikolai558/FE-BUDDY/assets/63331106/8e483ddc-a8ab-4a1a-8ecf-8ff100d5ee8a)

**Comment by KSanders7070** [comment]
Issue:
The FAA has changed the way their directory name is for some reason.
`NASR_Subscription_2023-11-02`
`NASR_Subscription/2023-11-02`

A fix will be released ASAP to grab the date index rather than splitting at an underscore.

**Comment by Nikolai558** [comment]
Fixed in [v2.6.9](https://github.com/Nikolai558/FE-BUDDY/releases/tag/2.6.9)
