### ISSUE TITLE
[BUG] - Missing Root Element Error (NWS Weather Stations)

### ISSUE THREAD

**Issue by Nikolai558** [Nikolai558/FE-BUDDY#163]
**Describe the bug**
Getting AIRAC Data fails with a bug message of "Missing Root Element"

**To Reproduce**
1.Run AIRAC data 
2.See bug
3.
4.

**Expected behavior**
Should run like any other time.

**Screenshots**

![image](https://github.com/Nikolai558/FE-BUDDY/assets/38259407/bbd0f451-2cb1-4d65-be98-3ae733e16310)

**Comment by Nikolai558** [comment]
NWS (National Weather Station) is revamping their website. In doing so they changed the link FE-Buddy Currently uses to retrieve all the Weather Stations for the NAS. Located in the [Download Helpers File](https://github.com/Nikolai558/FE-BUDDY/blob/9a8c11b90d0e81449408672683e49b6f6a6f9efa/FeBuddyLibrary/Helpers/DownloadHelpers.cs#L32)

The problem in FE-Buddy is this line of code in the [GetAptData](https://github.com/Nikolai558/FE-BUDDY/blob/9a8c11b90d0e81449408672683e49b6f6a6f9efa/FeBuddyLibrary/DataAccess/GetAptData.cs#L230)

This is the [new link](https://forecast.weather.gov/xml/current_obs/index.xml)
![image](https://github.com/Nikolai558/FE-BUDDY/assets/38259407/91806791-2b88-4b72-be82-4eae02bd13ee)


However, this bug can not be resolved until NWS fixes their website.

I found that the new link does not return anything except a "Page Not Found Error" and an [informational link](https://www.weather.gov/idp/forecastmigration) showing that they are aware of the links not existing. 

![image](https://github.com/Nikolai558/FE-BUDDY/assets/38259407/9eaa3c2a-fbbb-4db6-8899-431bca4c59f7)


Further detail and a list of changes can be found [here at the WX Gov Migration Link](https://www.weather.gov/idp/wxgovmigration) and [here at the Forecast Migration Link](https://www.weather.gov/idp/forecastmigration)

**Comment by KSanders7070** [comment]
it’s sloppy but screw it… it’s v2.x….

Change to the new link.

If download returns blank or does not exist, create a generic/blank output file with a single set of 00,00 coordinates.

This way it can continue with other functions. Don’t worry about making a fancy notification for this or anything, just include this process in the change log.

In v3.x we can keep in mind an alternative action if any file is not found or is corrupt for some reason.

**Comment by KSanders7070** [comment]
Also look into using this https://aviationweather.gov/data/api/#/Data/dataStationInfo

**Comment by Nikolai558** [comment]
Fixed in v2.7.0
