### ISSUE TITLE
[BUG] - CMP PDFs = 404

### ISSUE THREAD

**Issue by KSanders7070** [Nikolai558/FE-BUDDY#20]
PUBLICATIONS OUTPUT

When a procedure is deleted or added, FE-BUDDY still outputs a cmp link.

I think if the "recordModel.UserAction" is a A or D, the link should be not printed and instead display a quick explanation:
(D) "This procedure has been deleted this AIRAC."
(A) "This procedure is new and has no previous version to compare."

If the "recordModel.UserAction" is C but still returns a 404:
"This procedure has changed but the FAA does not seem to have a comparative document.  This is common with DOD facilities such as KHIF and KMUO."

If checking for the 404 takes too long, we can just make a general comment in the Instructions slides and print a general message at the top of each Procedure_Changes.txt file.

**Comment by Nikolai558** [comment]
Added / Fixed Version 1.0.2
