### ISSUE TITLE
[BUG] - Menu items change font/size randomly

### ISSUE THREAD

**Issue by Nikolai558** [Nikolai558/FE-BUDDY#22]
**Describe the bug**
When you open FE-Buddy and click on one of the menu items (i.e., "Instructions", "Roadmap") it will change sizes. Then after that happens, once you hover over any of the other menu items, they too will change sizes. 

**To Reproduce**
1. Run FE-Buddy
2. Click one Menu Item
3. Hover mouse over any other menu item

**Expected behavior**
The fonts / font size shouldn't change like this. 

**Screenshots**
![image](https://user-images.githubusercontent.com/38259407/146452628-44503427-b55e-493d-9d6d-e42bb00db17e.png)
![image](https://user-images.githubusercontent.com/38259407/146452690-c536d2fa-7688-4f93-992d-2f95a2723342.png)
![image](https://user-images.githubusercontent.com/38259407/146452741-920d741a-133f-4720-aa1c-338049f182e4.png)

**Comment by Nikolai558** [comment]
Fixed V1.0.2

**Comment by KSanders7070** [comment]
It is happening on my system now. Look at the Report Issues button... the left half of the R is cut off but wasn't like that until I clicked on it and it actually opened my browser.

Strange because I am about to reopen the other issue where it originally didn't open my browser when clicked. After restarting my browser, it worked but the font didn't change the first time when it failed to open the browser.

![image](https://user-images.githubusercontent.com/63331106/147030469-ba51420c-915d-4083-be86-eaaa8a187d50.png)

**Comment by KSanders7070** [comment]
After restarting FE-Buddy, the font doesnt seem to change.

**Comment by Nikolai558** [comment]
The only thing I can think of would be there is a problem with the custom renderer that we use.
I wonder if I need to add something for Font/Size in our custom renderer. This problem only started happening on my system after I implemented this custom renderer. 

```
private class MyRenderer : ToolStripProfessionalRenderer
        {
            public MyRenderer() : base(new MyColors()) { }
        }

        private class MyColors : ProfessionalColorTable
        {
            public override Color MenuItemSelected
            {
                get { return Color.Black; }
            }
            public override Color MenuItemSelectedGradientBegin
            {
                get { return Color.Black; }
            }
            public override Color MenuItemSelectedGradientEnd
            {
                get { return Color.Black; }
            }
            public override Color MenuItemPressedGradientBegin
            {
                get { return Color.Black; }
            }

            public override Color MenuItemPressedGradientEnd
            {
                get { return Color.Black; }
            }
        }
```

**Comment by Nikolai558** [comment]
Need further testing, Is this still a bug in 2.0.0 or greater?

**Comment by Nikolai558** [comment]
Due to the lack of activity on this issue, I am going to close it. If this issue continues in 2.1.1 or greater, please feel free to re-open or create a new issue. Thanks.
