### ISSUE TITLE
[FEAT REQ.] - Report Issue Button

### ISSUE THREAD

**Issue by KSanders7070** [Nikolai558/FE-BUDDY#23]
Button on the menu bar that takes them to the GitHub issues page.

THIS: https://github.com/Nikolai558/FE-BUDDY/issues

NOT THIS: https://github.com/Nikolai558/FE-BUDDY/issues/new/choose

We want them to see the current open tickets prior to filing one.

**Comment by Nikolai558** [comment]
Added V1.0.2
