### ISSUE TITLE
[BUG] - Generated VOR frequency format is not consistent

### ISSUE THREAD

**Issue by dylandxt** [Nikolai558/FE-BUDDY#36]
**Describe the bug**
VOR frequency format is not consistent. 

**To Reproduce**
1.  Freq in [VOR].sct2

**Expected behavior**
All freq should have the same format of xxx.xx?

**Screenshots**
![image](https://user-images.githubusercontent.com/99299646/155829788-6ff67fb9-a7f6-43c3-bf60-06da9b0f6e77.png)

**Comment by Nikolai558** [comment]
I agree. Thank you for the feedback!

**Comment by Nikolai558** [comment]
This has been fixed, lookout for the next release.

![image](https://user-images.githubusercontent.com/38259407/162592483-7534f956-1769-4aa0-9874-97b4b1270b45.png)
