### ISSUE TITLE
[FEAT REQ.] - Program Logger

### ISSUE THREAD

**Issue by KSanders7070** [Nikolai558/FE-BUDDY#4]
Originally filed with NASR2SCT issue 138.

Is your feature request related to a problem? Please describe.
Implement a logger.

Describe the solution you'd like
I'd like a logger implemented so that if weird events happen to users at random times I can see why it is happening. Also it is good practice to have a logger anyways. Have a button or option to "export/copy" the log file to the desktop.

Describe alternatives you've considered

Additional context

**Comment by KSanders7070** [comment]
Write a NASR2SCT_EVENT_LOG.log file that saves in the appdata folder.

The VERY first operation when program START would be to clear that log file.

A GUI button to copy that file to the desktop for easy access by user would be nice with an explanation to send it with bug reports for unexpected behavior.

**Comment by Nikolai558** [comment]
Added in V1.0.1. 

A simple logger was implemented, there are plans to upgrade the logger into a more advanced one. I am going to close this issue once released. However, the branch for the logger feature will be left open and continuously updated as logging needs arise.
