### ISSUE TITLE
[BUG] - SCT2 Comments formatting

### ISSUE THREAD

**Issue by KSanders7070** [Nikolai558/FE-BUDDY#45]
In the SCT2 [RUNWAY] section output, to remain consistent with the rest of the output, put a space before the ; and then remove the space after it before the comments.

current:
w123.59.59.999; comments

change to:

w123.59.59.999 ;comments

**Comment by KSanders7070** [comment]
Same with ARTCC HIGH

**Comment by KSanders7070** [comment]
Same with LOW AIRWAY

**Comment by KSanders7070** [comment]
Same with ARTCC LOW

**Comment by KSanders7070** [comment]
Same with SID/STAR output

**Comment by KSanders7070** [comment]
Ok.. seems like that is the STANDARD... but I suggest:

`<last bit of data><space><semicolon><no space><comments>`

**Comment by Nikolai558** [comment]
Fixed, Standard is `<last bit of data><space><semicolon><no space><comments>`
Will be in the next release.
