### ISSUE TITLE
[BUG] - STAR/DP Coordinate alignment

### ISSUE THREAD

**Issue by KSanders7070** [Nikolai558/FE-BUDDY#49]
The first character of the coordinates on every line should be the 27th character (26th index) of every line.

The first line of an individual diagram coordinates start at the 30th index while the actual coordinates (not the N000 ones) start correctly at the 26th index.

This does not create any issues but is not technically "correct".

Note: the "combined" diagrams are formatted correctly; It is only the individual diagram files that are affected.

**Comment by Nikolai558** [comment]
Fixed, will be in the next release.
