### ISSUE TITLE
[BUG] - Reading SCT2 Fixes in Place of Coordinates

### ISSUE THREAD

**Issue by KSanders7070** [Nikolai558/FE-BUDDY#55]
When the facility uses fix names in place of coordinates in diagrams and other objects, FEB needs to either:

1) Inform the user they can't do that in documentation

2) Analyze the file and detect that there are fixes where coordinates should be and throw a warning.

3) Store the fixes/navaids/airports for reference later and replace the fix with the coordinate when it comes across it.

Number 3 is the most ideal scenario but may require more work.

**Comment by Nikolai558** [comment]
FE buddy handles Fixes in place of Lat/Lon now.
