### ISSUE TITLE
[BUG] - Output Location not displaying

### ISSUE THREAD

**Issue by KSanders7070** [Nikolai558/FE-BUDDY#72]
Output Location not displaying in the Processing page anymore in v2.1.1. Works in v2.1.0

![image](https://user-images.githubusercontent.com/63331106/180575270-fae39475-583c-4eae-8b2f-632e84a57083.png)

**Comment by KSanders7070** [comment]
may be connected to #73

**Comment by Nikolai558** [comment]
It would seem I may have accidently deleted a part of code that was not suppose to be deleted...

https://github.com/Nikolai558/FE-BUDDY/compare/2.1.0...development#diff-4e19d885e61d4cc6f8852948f395860e452e3bd3f65a8e13adae0ab53aab2667L263
