### ISSUE TITLE
[FEAT REQ.] - Geo/Video Maps to GeoJSON

### ISSUE THREAD

**Issue by KSanders7070** [Nikolai558/FE-BUDDY#81]
To assist in preparation for CRC, users will need the ability to convert their vSTARS (ID) Video Maps.xml and vERAM (ID) GeoMaps.xml into GeoJSON.

vSTARS Default path: `%userprofile%\AppData\Roaming\vSTARS\Video Maps`

vERAM Default path: `%userprofile%\AppData\Local\vERAM\GeoMaps`

GeoJSON standards: [CRC Docs - Video Maps - Specs](https://data-admin.virtualnas.net/docs/#/video-maps?id=geojson-specification)

Each Video or GeoMap Object will need to be output into a single GEOJSON.

More information will be added below in comments

**Comment by KSanders7070** [comment]
### VERAM NOTES: Mixing Types into 1 Object

Though the ZLC ARTCC files attempt to not do this (and to my knowledge we were 100% successful) many ARTCCs will mix multiple `xsi:type`s into a single GeoMapObject.

When this happens, the FE will place the "Element Aspect Defaults" (not sure if this is what they are really called) after the GeoMapObject description and then will list all of the elements in **any** order below that.

![image](https://user-images.githubusercontent.com/63331106/181286819-b6de3f3d-398e-4159-bc76-c351c180dc2c.png)

Attached here you will find the example from the picture:
[Multi-Type GeoMapObject.xml.txt](https://github.com/Nikolai558/FE-BUDDY/files/9200501/Multi-Type.GeoMapObject.xml.txt)

**Comment by KSanders7070** [comment]
### VSTARS NOTES: Colors

vSTARS Video Maps have "Colors" associated with each line and I think for the purpose of getting this feature out sooner, we ignore that aspect for now.

**Comment by KSanders7070** [comment]
### FILE NAMES

We can take either the `Shortname` or `Longname` to make as the file name but do a search for any illegal characters and replace them with something like a dash or underscore.

**Comment by Nikolai558** [comment]
Should be completed, 

Potential feature changes coming in future versions, however, for right now this works as intended.
