### ISSUE TITLE
[TODO] - GeoJSON Antimeridian Crossing

### ISSUE THREAD

**Issue by KSanders7070** [Nikolai558/FE-BUDDY#82]
![image](https://user-images.githubusercontent.com/63331106/182264607-78ae6e1f-54ab-4326-a400-728663dc60b4.png)

**Comment by KSanders7070** [comment]
https://github.com/springmeyer/arc.js

**Comment by KSanders7070** [comment]
TESTING:

PATH: `-10.0,-170.0 10.0,170.0`  
The line should "break" at exactly this coordinate:
`0.0,180.0` or `-0.0,180.0` or `0.0,-180.0` or `-0.0,-180.0` (they are all the same coordinates).

This would result in a new path of:
```
-10.0,-170.0
-0.0,-180.0
```
<break>

```
-0.0,180.0
10.0,170.0
```

***

A less exact test:

Given a path of `55.0,-165.0 35.0,165.0`  
The line should "break" at approximately this coordinate:
`47.770691,-180.0`

This would result in a new path of:
```
55.0,-165.0
47.770691,-180.0
```
<break>

```
47.770691,180.0
165.0,35.0
```

***

We should also test in the other direction (From east to west).

Note: simply looking for a change in negative/positive longitudes will not suffice alone, as we are not concerned with a crossing of the Prime Meridian, only the Antemeridian.  
For example, the following path is of no concern to us:  
`45.0,-10.0 45.0,10.0`

**Comment by Nikolai558** [comment]
This should be fixed. We did alot of testing and everything looks correct.
