### ISSUE TITLE
[BUG] - Exception Catch "No type defaults"

### ISSUE THREAD

**Issue by KSanders7070** [Nikolai558/FE-BUDDY#87]
vSTARS/vERAM to GeoJSON

If the user doesn't define defaults but use a type, the user should be warned that is the case. This causes a crash if they don't have it defined currently.
![Screenshot_1](https://user-images.githubusercontent.com/63331106/183503394-26354552-6700-4cf2-ab16-31a8099ce62b.jpg)

**Comment by KSanders7070** [comment]
[ZOA GeoMaps.zip](https://github.com/Nikolai558/FE-BUDDY/files/9284639/ZOA.GeoMaps.zip)

**Comment by KSanders7070** [comment]
After some testing, I have realized that vERAM will just not show the text data in the case of the screenshot but will show the symbols.

**Comment by KSanders7070** [comment]
[ZOA GeoMaps.zip](https://github.com/Nikolai558/FE-BUDDY/files/9285380/ZOA.GeoMaps.zip)

**Comment by Nikolai558** [comment]
Fixed
