### ISSUE TITLE
[BUG] - ASDEX Color no name

### ISSUE THREAD

**Issue by KSanders7070** [Nikolai558/FE-BUDDY#88]
Screenshot from ZMA ARTCC, KMIA vSTARS file.
Also, the form title still references the metadata form (fixed in a push of mine)
![image](https://user-images.githubusercontent.com/63331106/183499987-fabe2cc1-47f6-413b-8722-e781fb17184f.png)
![image](https://user-images.githubusercontent.com/63331106/183514027-6db12c0a-7c2e-49de-b617-1a929840d2af.png)
![image](https://user-images.githubusercontent.com/63331106/183514366-a2926509-2f4b-4ffc-869b-b92e61bbfac5.png)

**Comment by KSanders7070** [comment]
[MIA Video Maps.zip](https://github.com/Nikolai558/FE-BUDDY/files/9284625/MIA.Video.Maps.zip)

**Comment by Nikolai558** [comment]
![image](https://user-images.githubusercontent.com/38259407/183532137-9d19559a-d524-450e-98a2-1ac7efe73f40.png)


If multiple Named colors = "" then it 'Empty_Color_Name' would show up "x" amount of times.

**Comment by Nikolai558** [comment]
Fixed, 

Might change how this works in a later version.
