### ISSUE TITLE
[FEAT REQ.] - vERAM/vSTARS maps default directory source

### ISSUE THREAD

**Issue by KSanders7070** [Nikolai558/FE-BUDDY#89]
for vERAM/vSTARS to GeoJSON, it would be nice if the SOURCE FILE button opened to the default directory where the associated source file type is stored. If the directory isn't found (such as when the user has their files stored on their /D drive, just open normally.

**Default location for the files:**
vSTARS: `%userprofile%\AppData\Roaming\vSTARS\Video Maps`
vERAM: `%userprofile%\AppData\Local\vERAM\GeoMaps`

**Comment by Nikolai558** [comment]
Added.
