### ISSUE TITLE
[BUG] - Default properties are being duplicated in feature-level properties.

### ISSUE THREAD

**Issue by nrankin18** [Nikolai558/FE-BUDDY#93]
**Describe the bug**

When an XML object has a property that's the same as the default, the default property should not be copied into the GeoJSON properties.

**Expected behavior**
The default line thickness is set to 1. GeoJSON Line Features should only contain a `thickness` property if that element's thickness is not 1. This prevents unnecessary data from being included in the GeoJSON

**Comment by Nikolai558** [comment]
This has been fixed v2.3.1.
