### ISSUE TITLE
[BUG] - Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by KSanders7070** [Nikolai558/FE-BUDDY#95]
![image](https://user-images.githubusercontent.com/63331106/184175010-817da529-bc7d-402e-9a89-83bdc997d3fb.png)
![image](https://user-images.githubusercontent.com/63331106/184175107-000dbc79-1477-4a92-a402-bf1d762e394a.png)

Might be caused by this?:
From my understanding, we can't have anything except WorldPoints in the ASDEX files.
See also: https://github.com/Nikolai558/FE-BUDDY/issues/92
![image](https://user-images.githubusercontent.com/63331106/184175085-0641b9f8-71c7-4773-8b72-933047d25116.png)

[D01 Video Maps.zip](https://github.com/Nikolai558/FE-BUDDY/files/9309978/D01.Video.Maps.zip)

**Comment by KSanders7070** [comment]
This may also be a situation where the FE has used a "color" in an Element but that color is not been defined in the COLORS section above it.

**Comment by Nikolai558** [comment]
This issue has been addressed in v2.3.2

It had to do with the xsi:type's that are inside an ASDEX map like Kyle stated above. 
The fix is to ignore the xsi:type's that do not equal "Path" (Polygons)
