### ISSUE TITLE
[BUG] - 3LD not printing

### ISSUE THREAD

**Issue by KSanders7070** [Nikolai558/FE-BUDDY#97]
Starting in v2.1.1, there was a change made intended to print the 3LD before the TELEPHONY but now it doesn't print the 3LD at all in v2.1.1 or later.

Reference:
https://github.com/Nikolai558/FE-BUDDY/commit/9582a15b286fa5f93737477f7362440ef1203f8a

**Comment by Nikolai558** [comment]
It is writing them to the "AliasTestFile.txt"
![image](https://user-images.githubusercontent.com/38259407/186917399-f1a2a8eb-e1a5-4b3f-aea4-7b520a320b98.png)

But it's not writing it to the "TELEPHONY.txt" file. 
![image](https://user-images.githubusercontent.com/38259407/186917508-8519eeb5-304b-40c8-ab60-ccca8febdb7f.png)

In the reference you mentioned above, the following correction should work. 
![image](https://user-images.githubusercontent.com/38259407/186918131-d80588c7-3317-423e-a660-0499e61b96d1.png)
